---
- name: Systemd - Force Systemd to Re-Execute itself & Reread Configs
  ansible.builtin.systemd_service:
    name: fail2ban.service
    state: started
    daemon_reexec: true
    daemon_reload: true
    
- name: Systemd - Restart Fail2Ban Service
  ansible.builtin.systemd_service:
    name: fail2ban.service
    state: restarted