---
- name: Install Packages - fail2ban
  ansible.builtin.apt:
    name: fail2ban
    state: latest
    update_cache: true

- name: Copy jail.local >> /etc/fail2ban/jail.local
  ansible.builtin.copy:
    src: ~/aws_lightsail_fail2ban_ips/include/scripts/jail.local
    dest: /etc/fail2ban/

- name: Systemd - Enable Fail2Ban Service
  ansible.builtin.systemd_service:
    name: fail2ban.service
    state: started
    enabled: true
  notify: 
    - Systemd - Force Systemd to Re-Execute itself & Reread Configs
    - Systemd - Restart Fail2Ban Service